### ISSUE TITLE
Generate package on AUR

### ISSUE THREAD

**Issue by ryukinix** [brain-labs/brain#28]

**Comment by rafaelcn** [comment]
Can I count on you both (@lerax, @Kuchiriel) to drop some ideas on the subject?

**Comment by ryukinix** [comment]
I have a count on AUR but don't have experience about creating packages on AUR. @Kuchiriel has more experience than me.

**Comment by Kuchiriel** [comment]
Send me the instructions, I'll do the remaining.

**Comment by ryukinix** [comment]
We need just compile the repository and create for now just the `brain-bin` on AUR.

**Comment by rafaelcn** [comment]
The purpose is pack up the Brain binaries located on `brain-bin` repository. In the end the user would have access to Brain by its terminal, the installation process will be:

* Install io.c on `/usr/local/include`
* Install brain binary on  `/usr/local/bin`

That way we don't bloat the system `/bin` folder. @luizperes do you want to add anything?

**Comment by luizperes** [comment]
I gotta check it and will answer you back!

Thanks

**Comment by Kuchiriel** [comment]
I will wait for @luizperes then.

**Comment by luizperes** [comment]
Hi @rafaelcn, actually, the `brain-bin` repository is for the binary scripts that we will generate, not for the binaries themselves, for example: The [docker one](https://github.com/brain-labs/brain-bin/blob/master/Docker/v1.0/Dockerfile). The binaries will be stored probably in a server.

The Library path is actually `/usr/local/include/brain` instead of `/usr/local/include` and it goes only `.ll`, not '.c', but the '.c' must be compiled to the target architecture.

@Kuchiriel If you can, could you generate the `AUR` one?

Thank you!

**Comment by Kuchiriel** [comment]
@luizperes I know there is a brain-bin repository, so, I can work from there, I just need the working binary files. But, guys, take a look at this repository https://github.com/haskellcamargo/skype-unofficial-client.

See the files structure, I need something like this to start. But in AUR we have the option to download the src and build on the machine, instead of copying binaries.

**Comment by ryukinix** [comment]
Well, maybe this is done for now: [brain](https://aur.archlinux.org/packages/brain/)

**Comment by ryukinix** [comment]
@ryukinix @luiz_peres

**Comment by luizperes** [comment]
Wow!!! Could you check it @rafaelcn?

**Comment by ryukinix** [comment]
Try install it via AUR and give some feedback later, @rafaelcn @Kuchiriel

**Comment by rafaelcn** [comment]
Good job @ryukinix, I can't check over here because I don't use an Arch base distro but it does looks it is working. We just need to generate the Debian installer now.

**Comment by ryukinix** [comment]
We need put this information on README.md. We can install brain with this command on ArchLinux (or another based distro just like Manjaro): `yaourt -S brain`

**Comment by Kuchiriel** [comment]
Brain is the number 25 in AUR. Packages 
With llvm-3.8.1-1 as dep.

Total Download Size:    18,64 MiB
Total Installed Size:  105,43 MiB

But...

Creating libraries...
./libs/install.sh: line 22: clang: command not found

You need to add clang compiler as dep.

**Comment by ryukinix** [comment]
@Kuchiriel Thanks, that way I'll just use clang instead gcc.

**Comment by ryukinix** [comment]
@Kuchiriel I update the PKGBUILD and .SRCINFO right now. Take a look later.

**Comment by rafaelcn** [comment]
GCC works just fine to compile Brain as well @ryukinix, although in the `libs/install.sh` file it only uses clang, we can change that if needed.

**Comment by ryukinix** [comment]
@rafaelcn The problem with clang is a warning about a inexistent flag -Un-not-maybe-initialized. Something like that.

**Comment by ryukinix** [comment]
but would be better if we can choose the compiler on lib script build

**Comment by luizperes** [comment]
You are right, @ryukinix. That warning is very annoying. For compiling Brain we will need either `gcc` or `clang`. Although @rafaelcn, I think that we can only use `clang` for the _Brain io.ll library_, because we are actually compiling it to `LLVM IR` rather than `binary code`, thus, I imagine that `gcc` does not __emit-llvm__, does it? For the `Brain v1.1`, I will try to take this clang dependecy out of the project. Moreover, thanks @ryukinix, @Kuchiriel and @rafaelcn for the good work!

**Comment by rafaelcn** [comment]
Well, I don't know either @luizperes, we have to try things out to know.

**Comment by luizperes** [comment]
@ryukinix can you include the process of installation using __AUR__ on the `README.md`? `yaourt -S brain`

**Comment by ryukinix** [comment]
Yes, I can do that.

**Comment by luizperes** [comment]
Thanks @ryukinix ! That was done on the PR #30
